### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by IdoBar** [johnlees/unitig-caller#24]
Hi,

I'm trying to run `unitig-caller` (v1.3.0 installed using `bioconda`) on an HPC using a population graph that I generated with `bifrost`.
The command I'm using is:
```
unitig-caller --call --graph Arab_pop_graph.gfa.gz --colours Arab_pop_graph.bfi --out Arab_pop_WGS_unitigs --pyseer --threads 8
```
And I'm getting the following output:
```
Calling unitigs within input genomes...
Reading coloured compacted DBG...
DataStorage::read(): Does not support more than 255 hash seeds
Calling unitigs within population...
Segmentation fault (core dumped)
```
This are the details of the operating system on the HPC:
```
LSB Version:    :core-4.1-amd64:core-4.1-noarch
Distributor ID: Rocky
Description:    Rocky Linux release 8.8 (Green Obsidian)
Release:        8.8
Codename:       GreenObsidian
```

Thanks, Ido

**Comment by samhorsfield96** [comment]
Hi Ido, I suspect the versions of Bifrost used to build the graph and in unitig-caller may be different, meaning unitig-caller cannot read the Bifrost input files. Would you be able to check this, please?

**Comment by IdoBar** [comment]
Hi @samhorsfield96 and thanks for the quick reply.
I've used `Bifrost` is v1.2.0 to generate the graphs, do you recommend trying with `unitig-caller` v1.2.0 or updating `Bifrost` to the recent version (v1.2.1)? Is the latest `Bifrost` compatible with `unitig-caller` v1.3.0

Thanks, Ido

**Comment by IdoBar** [comment]
I tried running with `unitig-caller` v1.2.0 (installed at a separate `conda` env and I'm getting the following error:
```
Traceback (most recent call last):
  File "/home/ibar/miniconda3/envs/gwas2/bin/unitig-caller", line 7, in <module>
srun: error: bun111: task 0: Exited with exit code 1
    from unitig_caller.__main__ import main
  File "/home/ibar/miniconda3/envs/gwas2/lib/python3.9/site-packages/unitig_caller/__main__.py", line 11, in <module>
    import unitig_query
ImportError: /home/ibar/miniconda3/envs/gwas2/lib/python3.9/site-packages/unitig_query.cpython-39-x86_64-linux-gnu.so: undefined symbol: _ZN12KmerIteratordeEv
```
Any idea what's happening?

**Comment by samhorsfield96** [comment]
Hi Ido, the version of Bifrost used to build the graph (v1.2.0) needs to match that used in the unitig-caller environment. I don't believe the version of unitig-caller should matter in this case, as the functions from Bifrost that are used are the same, it is just the graph data structure that is different. I would suggest reinstalling unitig-caller and specifying the Bifrost version you require. 

For example:

conda install unitig-caller bifrost=1.2.0
