### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by DorothyTamYiLing** [johnlees/unitig-caller#26]
Hi, 

I have an error after installing using the following command:
conda create --name unitig-caller unitig-caller

(unitig-caller) tyl205@nimbus-1-login-1 /campaign/AB-BB0112-002 $ unitig-caller -h
Traceback (most recent call last):
  File "/shared/home/tyl205/miniconda3/envs/unitig-caller/bin/unitig-caller", line 7, in <module>
    from unitig_caller.__main__ import main
  File "/shared/home/tyl205/miniconda3/envs/unitig-caller/lib/python3.10/site-packages/unitig_caller/__main__.py", line 11, in <module>
    import unitig_query
ImportError: /shared/home/tyl205/miniconda3/envs/unitig-caller/lib/python3.10/site-packages/unitig_query.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN18BlockedBloomFilter15ReadBloomFilterEP8_IO_FILE

It is similar error to issue [20](https://github.com/bacpop/unitig-caller/issues/20) (it is now closed), however it is not very clear to me in the comments what I should do to solve the issue. How do I pin the Bifrost version during installation?

Thanks,
Dorothy

**Comment by samhorsfield96** [comment]
Hi Dorothy, which version of Bifrost is installed in the `unitig-caller` conda environment?

**Comment by samhorsfield96** [comment]
Hi Dorothy, I believe issue #28 describes a similar problem. There is a new build of unitig-caller that should be available on bioconda soon. Please give this a try and let us know if the issue persists.
